### ISSUE TITLE
bot启动时报错

### ISSUE THREAD

**Issue by BlackTitle** [pcrbot/HoshinoBot-plugins-index#139]
错误代码段:

### `[2022-06-19 20:43:37,027 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc3.create_img", error: Expecting ':' delimiter: line 3 column 11 (char 27)
[2022-06-19 20:43:37,028 nonebot] ERROR: Expecting ':' delimiter: line 3 column 11 (char 27)
Traceback (most recent call last):
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\BOT\HoshinoBot-master\hoshino\modules\pcrjjc3\__init__.py", line 87, in <module>
    pinfo = load(fp)
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 3 column 11 (char 27)`

环境:
Windows 11 Dev 、 Python 3.9.7 
已安装 requirements.txt 已尝试卸载再安装 requirements.txt
hoshino为自安装非一键包
好像没了？

**Comment by yuudi** [comment]
你好，本仓库收集 HoshinoBot 的第三方作品，仅作为索引查询使用
插件问题请到相应插件仓库交流
<https://github.com/azmiao/pcrjjc3-tw>
